#!/bin/sh

#SBATCH --job-name=ith_search
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=1-12:00:00
#SBATCH --mem-per-cpu=4gb

SEARCHLIGHT="$1"
X="$2"
Y="$3"
OUTPUTDIR="$4"
SCRIPTDIR="$5"

python "$SCRIPTDIR/ith_searchlight.py" "$SEARCHLIGHT" "$X" "$Y" "$OUTPUTDIR"