#!/bin/sh

#SBATCH --job-name=time_gen
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
TSVDIR="$3"
SCRIPTDIR="$4"

python "$SCRIPTDIR/svc_time_generalization.py" "$INPUTDIR" "$OUTPUTDIR" "$TSVDIR"