#!/bin/sh

#SBATCH --job-name=mvpa_glm
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=16gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
MASKFILE="$3"
TMAP="$4"
SCRIPTDIR="$5"

python "$SCRIPTDIR/svc_beta.py" "$INPUTDIR" "$OUTPUTDIR" "$MASKFILE" "$TMAP" "$TSVDIR"