#!/bin/sh

#SBATCH --job-name=control
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=1gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

TSVDIR="$1"
OUTPUTDIR="$2"
SCRIPTDIR="$3"

python "$SCRIPTDIR/svc_control.py" "$TSVDIR" "$OUTPUTDIR"