#!/bin/sh

#SBATCH --job-name=contrast
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=4gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
TSVDIR="$3"
SCRIPTDIR="$4"

python "$SCRIPTDIR/svc_contrast.py" "$INPUTDIR" "$OUTPUTDIR" "$TSVDIR"