#!/bin/sh

#SBATCH --job-name=searchlight
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=2-12:00:00
#SBATCH --mem-per-cpu=3gb

INPUTDIR="$1"
OUTPUTDIR="$2"
WORKINGDIR="$3"
ANATDIR="$4"
ITERATION="$5"
SCRIPTDIR="$6"

python "$SCRIPTDIR/svc_searchlight.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$ITERATION" "$SCRIPTDIR"