#!/bin/sh

#SBATCH --job-name=mvpa
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=6:00:00
#SBATCH --mem-per-cpu=48gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
WORKINGDIR="$3"
MASKFILE="$4"
TMAP="$5"
TSVDIR="$6"
SCRIPTDIR="$7"

# python "$SCRIPTDIR/svc_analysis_tr.py" "$INPUTDIR" "$OUTPUTDIR" "$TSVDIR"
python "$SCRIPTDIR/svc_analysis.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$MASKFILE" "$TMAP" "$TSVDIR"