#!/bin/sh
#SBATCH --job-name=boco
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=8:00:00
#SBATCH --mem=500

VASO=$1
BOLD=$2

DIR=`dirname "$VASO"`
VASO=`basename "$VASO"`
BOLD=`basename "$BOLD"`

cd $DIR

LN_CORREL2FILES -file1 $VASO -file2 $BOLD
