#!/bin/sh
#SBATCH --job-name=boco
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=8:00:00
#SBATCH --mem=2000

VASO=$1
BOLD=$2

DIR=`dirname "$VASO"`
VASO=`basename "$VASO"`
BOLD=`basename "$BOLD"`

cd $DIR

SHIFT=0.43

export FSLOUTPUTTYPE=NIFTI

# shift notnulled (BOLD)
slicetimer -i $BOLD -o intemp_$BOLD --tglobal=-$SHIFT

# BOLD correction
fslmaths  $VASO -div intemp_$BOLD -max 0 -min 5 corr_$VASO