#!/bin/sh

#SBATCH --job-name=normalize
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem=8gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
WORKINGDIR="$3"
SCRIPTDIR="$4"
SPMDIR="$5"

python "$SCRIPTDIR/normalize.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$SPMDIR"
