#!/bin/sh

#SBATCH --job-name=pre_boco
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=1:00:00
#SBATCH --mem=10
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
SCRIPTDIR="$3"

START=1
END=10

index=0
for RUN in $(seq $START $END); do
  for sub in 'sub-08' 'sub-09'; do
      bold_dir[$index]="$INPUTDIR/$sub/func/r"$sub"_task-img_run-$(printf "%02d" "$RUN")_bold.nii"
      # bold_dir[$index]="$INPUTDIR/$sub/func/intemp_r"$sub"_task-img_run-$(printf "%02d" "$RUN")_bold.nii"
      vaso_dir[$index]="$INPUTDIR/$sub/func/r"$sub"_task-img_run-$(printf "%02d" "$RUN")_vaso.nii"
      index=$((index + 1))
  done
done

current_bold_dir=(${bold_dir[${SLURM_ARRAY_TASK_ID}]})
current_vaso_dir=(${vaso_dir[${SLURM_ARRAY_TASK_ID}]})

sbatch "$SCRIPTDIR/bold_correction" "$current_vaso_dir" "$current_bold_dir"
# sbatch "$SCRIPTDIR/bold_vaso_correlation" "$current_vaso_dir" "$current_bold_dir"