#!/bin/sh

#SBATCH --job-name=preregistration
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=4
#SBATCH --mail-type=END
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

BASEDIR="$1"
SCRIPTDIR="$2"

declare -a combinations
index=0
  # for sub in 'sub-01' 'sub-02' 'sub-03' 'sub-04' 'sub-05' 'sub-06' 'sub-07'; do
  for sub in "sub-04"; do
    # for type in 'NoRigid' 'SyN' 'Affine' 'AP'; do
    for type in 'AP' "NoRigid" "SyN" "Affine"; do
      combinations[$index]="$sub $type"
      index=$((index + 1))
  done
done

parameters=(${combinations[${SLURM_ARRAY_TASK_ID}]})

SUB=${parameters[0]}
TYPE=${parameters[1]}

if [ "$TYPE" == "NoRigid" ]; then
  SUBDIR="reg1"
fi
if [ "$TYPE" == "SyN" ]; then
  SUBDIR="reg2"
fi
if [ "$TYPE" == "Affine" ]; then
  SUBDIR="reg3"
fi
if [ "$TYPE" == "AP" ]; then
  SUBDIR="reg4"
fi
if [ "$TYPE" == "CON" ]; then
  SUBDIR="reg5"
fi

# MOVINGIMAGE="$BASEDIR/$SUB/anat/freesurfer/mri/orig.nii"
# MOVINGIMAGE="$BASEDIR/$SUB/func/str_bc_mean"$SUB"_task-img_run-01_vaso.nii"
MOVINGIMAGE="$BASEDIR/$SUB/func/masked_mean"$SUB"_task-loc_run-01_bold.nii"
FIXEDIMAGE="$BASEDIR/$SUB/anat/freesurfer/mri/brainmask.nii"
MASK="$BASEDIR/$SUB/mask/mask.nii"
MATRIX="$BASEDIR/$SUB/func/initial_matrix.txt"
OUTPUTDIR="$BASEDIR/$SUB/func/$SUBDIR"

if [ ! -d "$OUTPUTDIR" ]; then
  mkdir "$OUTPUTDIR"
fi

echo $FIXEDIMAGE
echo $MOVINGIMAGE
echo $MASK
echo $MATRIX
echo $OUTPUTDIR

if [ -d "$OUTPUTDIR" ] && [ -f "$FIXEDIMAGE" ] && [ -f "$MOVINGIMAGE" ] && [ -f "$MASK" ] && [ -f "$MATRIX" ]; then
  sbatch "$SCRIPTDIR"/ants_registration "$FIXEDIMAGE" "$MOVINGIMAGE" "$MASK" "$MATRIX" "$OUTPUTDIR" "$TYPE"
fi
