#!/bin/sh

#SBATCH --job-name=smooth
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=88:00:00
#SBATCH --mem=90000
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

# MEM VASO = 3Gb
# MEM BOLD = ?

INPUTDIR="$1"
SCRIPTDIR="$3"

START=1
END=12

index=0
for RUN in $(seq $START $END); do
  for sub in 'sub-07'; do
  # for sub in 'sub-01' 'sub-02' 'sub-03' 'sub-04' 'sub-05' 'sub-06' 'sub-07'; do
      nifti_dir[$index]="$INPUTDIR/$sub/func/cr_r"$sub"_task-img_run-$(printf "%02d" "$RUN")_bold.nii"
      # nifti_dir[$index]="$INPUTDIR/$sub/func/corr_r"$sub"_task-img_run-$(printf "%02d" "$RUN")_vaso.nii"
      index=$((index + 1))
  done
done

current_nifti_dir=(${nifti_dir[${SLURM_ARRAY_TASK_ID}]})

echo "smoothing time series"
echo $current_nifti_dir
# python "$SCRIPTDIR/standarize_img.py" "$current_nifti_dir"
python "$SCRIPTDIR/smooth_img.py" "$current_nifti_dir"
