#!/bin/sh

#SBATCH --job-name=nulled
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=1300
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
SCRIPTDIR="$3"

python "$SCRIPTDIR/split_nulled_not_nulled.py" "$INPUTDIR" "$OUTPUTDIR"