#!/bin/sh

#SBATCH --job-name=vaso_correction
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=2500
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
SCRIPTDIR="$3"

python "$SCRIPTDIR/vaso_bold_correction.py" "$INPUTDIR" "$OUTPUTDIR"