#!/bin/sh

#SBATCH --job-name=multi_z-score
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=4
#SBATCH --mail-type=END
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR=$1
LAYERDIR=$2
SCRIPTDIR=$3

START=1
END=12

index=0
for RUN in $(seq $START $END); do
  # for sub in 'sub-01'; do
  for sub in 'sub-01' 'sub-02' 'sub-03' 'sub-06' 'sub-07' 'sub-08' 'sub-09' 'sub-10' 'sub-11' 'sub-12' 'sub-13' 'sub-14' 'sub-15' 'sub-16' 'sub-17' 'sub-18'; do
      nifti_dir[$index]="$INPUTDIR/$sub/func/cr_r"$sub"_task-img_run-$(printf "%02d" $RUN)_bold.nii"
      layer_dir[$index]="$INPUTDIR/$sub/mask/layer_mask_FFA-PPA.nii"
      index=$((index + 1))
      # sbatch "$SCRIPTDIR/multi_devein" "$beta_dir" "$LAYERDIR" "$COLUMNDIR" "$ALFNIIDIR"
    done
  done
size=${#nifti_dir}
echo $index
current_dir=(${nifti_dir[${SLURM_ARRAY_TASK_ID}]})
l_dir=(${layer_dir[${SLURM_ARRAY_TASK_ID}]})

sbatch "$SCRIPTDIR/z-score_img" "$current_dir" "$l_dir" "$SCRIPTDIR"

