#!/bin/sh

#SBATCH --job-name=realign
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=2
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=2gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
SPMDIR="$3"
MATLABDIR="$4"
SCRIPTDIR="$5"

cd $INPUTDIR
# rm *txt
# rm *mat

python "$SCRIPTDIR/spm_realignment.py" "$INPUTDIR" "$OUTPUTDIR" "$SPMDIR" "$MATLABDIR"