#!/bin/sh

#SBATCH --job-name=topup
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=2
#SBATCH --qos=standard
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=1800
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
JSONFILE="$3"
SCRIPTDIR="$4"

python "$SCRIPTDIR/topup.py" "$INPUTDIR" "$OUTPUTDIR" "$JSONFILE" # "$SCRIPTDIR"