#!/bin/sh

#SBATCH --job-name=bias_correction
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#SBATCH --mem=16gb
#SBATCH --qos=standard
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
WORKINGDIR="$3"
TPMDIR="$4"
PIPELINEDIR="$5"

matlab -nodisplay -nosplash -nodesktop -r "cd('$PIPELINEDIR'); bias_field_correction('$INPUTDIR', '$WORKINGDIR', '$TPMDIR'); exit"

cd $INPUTDIR
mv `ls *fwhm*` "$OUTPUTDIR"
mv `ls *.mat` "$OUTPUTDIR"