#!/bin/sh

#SBATCH --job-name=mp2rage_reconall
#SBATCH --nodes=1
#SBATCH --time=96:00:00
#SBATCH --mem=16gb
#SBATCH --qos=standard
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
SPMDIR="$3"
SCRIPTDIR="$4"

mri_convert $INPUTDIR/*INV1*.nii.gz $INPUTDIR/INV1.nii
mri_convert $INPUTDIR/*INV2*.nii.gz $INPUTDIR/INV2.nii
mri_convert $INPUTDIR/*UNI*.nii.gz $INPUTDIR/UNI.nii
#
cd $INPUTDIR
mv 'UNI.nii' "$OUTPUTDIR"
mv 'INV2.nii' "$OUTPUTDIR"

python "$SCRIPTDIR/anatomy_dc.py" "$OUTPUTDIR" "$OUTPUTDIR" "$SPMDIR"