#!/bin/sh

#SBATCH --job-name=autorecon2
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=96gb
#SBATCH --qos=standard
#SBATCH --time=96:00:00
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

OUTPUTDIR="$1"
WORKINGDIR="$2"

recon-all -autorecon2 -autorecon3 -s "freesurfer" -sd "$OUTPUTDIR" -hires -xopts-overwrite' ' -expert "$WORKINGDIR" -parallel