#!/bin/sh

#SBATCH --job-name=layerification
#SBATCH --ntasks=1
#SBATCH --qos=standard
#SBATCH --time=01:00:00
#SBATCH --mem-per-cpu=2gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"

echo $OUTPUTDIR
cd "$OUTPUTDIR"
# mri_convert ribbon.mgz ribbon.nii
# LN2_RIMIFY -input ribbon.nii -innergm 2 -outergm 0 -gm 3 -output rh_ribbon.nii
# LN2_RIMIFY -input ribbon.nii -innergm 41 -outergm 0 -gm 42 -output lh_ribbon.nii

# LN2_LAYERS -rim rh_ribbon.nii -equivol -output rh
# LN2_LAYERS -rim lh_ribbon.nii -equivol -output lh

LN2_COLUMNS -rim rh_ribbon.nii -midgm rh_midGM_equivol.nii -nr_columns 20000
LN2_COLUMNS -rim lh_ribbon.nii -midgm lh_midGM_equivol.nii -nr_columns 20000

# LN2_LAYERS -rim rim.nii -equivol -nr_layers 3
LN2_COLUMNS -rim rim.nii -midgm rim_midGM_equivol.nii -nr_columns 20000 -output manual