#!/bin/sh

#SBATCH --job-name=upsample
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem=3000
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

# MEM 15GB to upsample mean4D
ANAT="$1"
FUNC="$2"
TMAP="$3"
MASK="$4"
VASO_BETA="$5"
BOLD_BETA="$6"

PATHDIR1=`dirname "$ANAT"`
PATHDIR2=`dirname "$TMAP"`
PATHDIR3=`dirname "$MASK"`

FILENAME1=`basename "$ANAT"`
FILENAME2=`basename "$TMAP"`
FILENAME3=`basename "$MASK"`

# DIR=/Users/carricarte/scratch/projects/imagery/main/vaso/derivatives/sub-01/func
# FILE=bold_tsnr.nii
# ResampleImage 3 $DIR/$FILE $DIR/up_$FILE  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $ANAT $PATHDIR1/up_$FILENAME1  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $TMAP $PATHDIR2/up_$FILENAME2  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $MASK $PATHDIR3/up_$FILENAME3  0.4x0.4x0.4 0 1 6
#ResampleImage 3 $VASO_BETA/mean_z-score_0001.nii $VASO_BETA/up_mean_z-score_0001.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean_z-score_0002.nii $VASO_BETA/up_mean_z-score_0002.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean_z-score_0003.nii $VASO_BETA/up_mean_z-score_0003.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean_z-score_0003.nii $BOLD_BETA/up_mean_z-score_0003.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean_z-score_0001.nii $BOLD_BETA/up_mean_z-score_0001.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean_z-score_0002.nii $BOLD_BETA/up_mean_z-score_0002.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $VASO_BETA/mean_beta_seen_place.nii $VASO_BETA/up_mean_beta_seen_place.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $VASO_BETA/mean_beta_img_place.nii $VASO_BETA/up_mean_beta_img_place.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $BOLD_BETA/mean_beta_seen_place.nii $BOLD_BETA/up_mean_beta_seen_place.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $BOLD_BETA/mean_beta_img_place.nii $BOLD_BETA/up_mean_beta_img_place.nii  0.4x0.4x0.4 0 3['l'] 6
ResampleImage 3 $VASO_BETA/psc_seen_place.nii $VASO_BETA/up_psc_seen_place.nii  0.4x0.4x0.4 0 3['l'] 6
ResampleImage 3 $VASO_BETA/psc_img_place.nii $VASO_BETA/up_psc_img_place.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $BOLD_BETA/psc_seen_place.nii $BOLD_BETA/up_psc_seen_place.nii  0.4x0.4x0.4 0 3['l'] 6
# ResampleImage 3 $BOLD_BETA/psc_img_place.nii $BOLD_BETA/up_psc_img_place.nii  0.4x0.4x0.4 0 3['l'] 6

#ResampleImage 3 $BOLD_BETA/mean-img_place_tr-1.nii $BOLD_BETA/up_mean-img_place_tr-1.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean-img_place_tr-2.nii $BOLD_BETA/up_mean-img_place_tr-2.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean-img_place_tr-3.nii $BOLD_BETA/up_mean-img_place_tr-3.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean-seen_place_tr-1.nii $BOLD_BETA/up_mean-seen_place_tr-1.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean-seen_place_tr-2.nii $BOLD_BETA/up_mean-seen_place_tr-2.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $BOLD_BETA/mean-seen_place_tr-3.nii $BOLD_BETA/up_mean-seen_place_tr-3.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-img_place_tr-1.nii $VASO_BETA/up_mean-img_place_tr-1.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-img_place_tr-2.nii $VASO_BETA/up_mean-img_place_tr-2.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-img_place_tr-3.nii $VASO_BETA/up_mean-img_place_tr-3.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-seen_place_tr-1.nii $VASO_BETA/up_mean-seen_place_tr-1.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-seen_place_tr-2.nii $VASO_BETA/up_mean-seen_place_tr-2.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 $VASO_BETA/mean-seen_place_tr-3.nii $VASO_BETA/up_mean-seen_place_tr-3.nii  0.4x0.4x0.4 0 3['l'] 6

# ResampleImage 4 $FUNC/mean4d_bold_per.nii $FUNC/up_mean4d_bold_per.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_bold_img.nii $FUNC/up_mean4d_bold_img.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_vaso_per.nii $FUNC/up_mean4d_vaso_per.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_vaso_img.nii $FUNC/up_mean4d_vaso_img.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_psc_bold.nii $FUNC/up_mean4d_psc_bold.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_nm_bold.nii $FUNC/up_mean4d_nm_bold.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_vaso.nii $FUNC/up_mean4d_vaso.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_psc_vaso.nii $FUNC/up_mean4d_psc_vaso.nii 0.4x0.4x0.4x1 0 4
# ResampleImage 4 $FUNC/mean4d_nm_vaso.nii $FUNC/up_mean4d_nm_vaso.nii 0.4x0.4x0.4x1 0 4

# ResampleImage 3 $BOLD_BETA/effect_size_seen_places.nii $BOLD_BETA/up_effect_size_seen_places.nii  0.4x0.4x0.4 0 3['l'] 6
#ResampleImage 3 "$PATHDIR3/right_mask.nii" "$PATHDIR3/up_right_mask.nii"  0.4x0.4x0.4 0 1 6
#ResampleImage 3 "$PATHDIR3/left_mask.nii" "$PATHDIR3/up_left_mask.nii"  0.4x0.4x0.4 0 1 6

#ORI=`fslorient -getsform $PATHDIR1/up_$FILENAME1`
#fslorient -setsform $ORI $PATHDIR3/up_$FILENAME3
#
# fslmaths $PATHDIR1/up_$FILENAME1 -mas $MASK $PATHDIR1/mk_$FILENAME1
#
# fast -n 3 -o $PATHDIR1/sg_$FILENAME1 $PATHDIR1/mk_$FILENAME1.gz
# LN2_RIMIFY -input $PATHDIR1/sg_$FILENAME1_seg.nii.gz -innergm 3 -outergm 1 -gm 2
