#!/bin/sh
#SBATCH --job-name=mriqc
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=24gb
#SBATCH --qos=standard
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de
	
	INPUTDIR="$1"
	OUTPUTDIR="$2"
	SUBJECT="$3"
	
	echo ""
	echo "Running MRIQC"
	echo ""

	#singularity pull --name mriqc_latest.sif docker://poldracklab/mriqc:latest	
	singularity run --cleanenv --bind "$INPUTDIR":/data --bind "$OUTPUTDIR":/out \
	mriqc_latest.sif \
	/data /out participant \
	--participant_label "$SUBJECT" --no-sub \
	--n_procs 8 --mem_gb 24