#!/bin/sh

#SBATCH --job-name=dataframe
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=96:00:00
#SBATCH --mem-per-cpu=48gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
MASKFILE="$3"
TMAP="$4"
SCRIPTDIR="$5"
LAYER="$6"

python "$SCRIPTDIR/nifti2dframe.py" "$INPUTDIR" "$OUTPUTDIR" "$MASKFILE" "$TMAP" "$LAYER"