#!/bin/sh

#SBATCH --job-name=1_level
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=48:00:00
#SBATCH --mem-per-cpu=3100
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de


INPUTDIR="$1"
OUTPUTDIR="$2"
WORKINGDIR="$3"
MASK="$4"
SCRIPTDIR="$5"

# python "$SCRIPTDIR/glm_analysis_task_img.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$SUBJECT" "$SPMDIR" "$MATLABDIR"
# python "$SCRIPTDIR/glm_analysis_task_loc.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$SUBJECT" "$SPMDIR" "$MATLABDIR"
python "$SCRIPTDIR/nilearn_first_level_vaso.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR"
# python "$SCRIPTDIR/nilearn_first_level_bold.py" "$INPUTDIR" "$OUTPUTDIR" "$WORKINGDIR" "$MASK"