#!/bin/sh

#SBATCH --job-name=univariate
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --qos=standard
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=48gb
#SBATCH --mail-type=end
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de

INPUTDIR="$1"
OUTPUTDIR="$2"
TSVDIR="$3"
MASKFILE="$4"
TMAP="$5"
SCRIPTDIR="$6"


python "$SCRIPTDIR/univariate_avg.py" "$INPUTDIR" "$OUTPUTDIR" "$TSVDIR" "$MASKFILE" "$TMAP"