#!/bin/sh

#SBATCH --job-name=bids_dcm2niix
#SBATCH --mail-user=carricarte@zedat.fu-berlin.de
#SBATCH --mail-type=end
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=2gb
#SBATCH --time=03:00:00
#SBATCH --qos=standard


INPUTDIR="$1"
SUBJECT="$2"

#module load singularity
singularity run --bind $INPUTDIR:/mnt bidskit.sif  --indir=/mnt/sourcedata/incoming --outdir=/mnt/rawdata --no-sessions